[package]
name = "agtmux-tmux-v5"
version = "0.1.0"
edition = "2024"

[dependencies]
agtmux-core-v5.workspace = true
agtmux-source-poller.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
