[package]
name = "agtmux-source-poller"
version = "0.1.0"
edition = "2024"

[dependencies]
agtmux-core-v5 = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
